apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: coffeeshop-hpa
  namespace: keptndemo
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: javacoffeeshop-deployment
  minReplicas: 1
  maxReplicas: 5
  metrics:
    - type: Object
      object:
        metric:
          name: cpu-throttling
        describedObject:
          apiVersion: metrics.keptn.sh/v1alpha3
          kind: KeptnMetric
          name: cpu-throttling
        target:
          type: AverageValue
          averageValue: 95000m
