apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-deployment
  namespace: keptndemo
  labels:
    app.kubernetes.io/name: coffeeshop
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: coffeeshop
  template:
    metadata:
      labels:
        app.kubernetes.io/part-of: keptndemoapp
        app.kubernetes.io/name: coffeeshop
        app.kubernetes.io/version: 0.0.1
    spec:
      containers:
      - name: coffeeshop
        image: shmdus/java-app:15
        resources:
          limits:
            cpu: 5m
            memory: 128Mi
          requests:
            cpu: 1m
            memory: 64Mi        
        ports:
        - containerPort: 8083
---
apiVersion: v1
kind: Service
metadata:
  name: java-svc
  namespace: keptndemo
spec:
  selector:
    app.kubernetes.io/name: coffeeshop
  type: NodePort
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8083
      nodePort: 30000
