apiVersion: apps/v1
kind: Deployment
metadata:
  name: javacoffeeshop-deployment
  namespace: keptndemo
  labels:
    app.kubernetes.io/name: javacoffeeshop
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: javacoffeeshop
  template:
    metadata:
      labels:
        app.kubernetes.io/part-of: keptndemoapp
        app.kubernetes.io/name: javacoffeeshop
        app.kubernetes.io/version: 0.0.3
    spec:
      containers:
      - name: javacoffeeshop
        image: shmdus/java-app:18
        ports:
        - containerPort: 8083
        resources:
          limits:
            cpu: 500m
            memory: 400Mi
          requests:
            cpu: 160m
            memory: 200Mi
---
apiVersion: v1
kind: Service
metadata:
  name: javacoffeeshop
  namespace: keptndemo
spec:
  selector:
    app.kubernetes.io/name: javacoffeeshop
  ports:
    - protocol: TCP
      port: 8080
      nodePort: 30450
      targetPort: 8083
