apiVersion: apps/v1
kind: Deployment
metadata:
  name: javacoffeeshop-deployment
  namespace: keptndemo
  labels:
    app.kubernetes.io/name: javacoffeeshop
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: javacoffeeshop
  template:
    metadata:
      labels:
        app.kubernetes.io/part-of: keptndemoapp
        app.kubernetes.io/name: javacoffeeshop
        app.kubernetes.io/version: 0.0.6
        keptn.sh/post-deployment-tasks: "send-event"
    spec:
      containers:
      - name: javacoffeeshop
        image: 'goksatexpleo/javacoffeeshopkeptn:1'
        ports:
        - containerPort: 8083
        resources:
          limits:
            cpu: 20m
            memory: 500Mi
          requests:
            cpu: 7m
            memory: 250Mi

---
apiVersion: apps/v1
kind: Service
apiVersion: v1
kind: Service
metadata:
  name: javacoffeeshop
  namespace: keptndemo
spec:
  selector:
    app.kubernetes.io/name: javacoffeeshop
  ports:
    - protocol: TCP
      port: 8080
      nodePort: 30450
      targetPort: 8083
