apiVersion: lifecycle.keptn.sh/v1alpha3
kind: KeptnTaskDefinition
metadata:
  name: post-deploy-task
  namespace: keptndemo
spec:
  container:
    name: postcheck
    image: curlimages/curl
    command:
      - /bin/bash
      - -c
      - sleep
      - '3600'
      - curl http://javacoffeeshop.keptndemo:8080
