apiVersion: lifecycle.keptn.sh/v1alpha3
kind: KeptnTaskDefinition
metadata:
  name: pre-deploy-task
  namespace: keptndemo
spec:
  container:
    name: check
    image: ubuntu:20.4
    command:
      - /bin/bash
      - -c
      - |
        sudo apt-get install wget apt-transport-https gnupg lsb-release
        wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key | gpg --dearmor | sudo tee /usr/share/keyrings/trivy.gpg > /dev/null
        echo "deb [signed-by=/usr/share/keyrings/trivy.gpg] https://aquasecurity.github.io/trivy-repo/deb $(lsb_release -sc) main" | sudo tee -a /etc/apt/sources.list.d/trivy.list
        sudo apt-get update
        sudo apt-get install trivy
        # wget https://github.com/mdapps95/keptn-klt/blob/main/deploy.yaml
        # trivy fs --scanners ./deploy.yaml
        echo "Hello-world"
