apiVersion: lifecycle.keptn.sh/v1alpha3
kind: KeptnTaskDefinition
metadata:
  name: pre-deploy-task
  namespace: keptndemo
spec:
  container:
    name: check
    image: ubuntu
    command:
      - /bin/sh
      - -c
      - |
        apt-get install wget apt-transport-https gnupg lsb-release -y
        wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key | gpg --dearmor | tee /usr/share/keyrings/trivy.gpg > /dev/null
        echo "deb [signed-by=/usr/share/keyrings/trivy.gpg] https://aquasecurity.github.io/trivy-repo/deb $(lsb_release -sc) main" | tee -a /etc/apt/sources.list.d/trivy.list
        apt-get update
        apt-get install trivy -y
        wget https://github.com/mdapps95/keptn-klt/blob/main/deploy.yaml
        trivy fs --scanners ./deploy.yaml
