apiVersion: v1
kind: Service
metadata:
  name: javacoffeeshop
  namespace: keptndemo
spec:
  selector:
    app.kubernetes.io/name: javacoffeeshop
  ports:
      type: NodePort
      port: 8080
      nodePort: 30450
      targetPort: 8083
