apiVersion: v1
kind: Service
metadata:
  name: javacoffeeshop
spec:
  selector:
    app.kubernetes.io/name: javacoffeeshop
  type: NodePort
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8083
      nodePort: 30450
