apiVersion: v1
kind: Service
metadata:
  name: javacoffeeshop
  namespace: keptndemo
spec:
  selector:
    app.kubernetes.io/name: javacoffeeshop
  ports:
    - protocol: TCP
      type: NodePort
      port: 8080
      targetPort: 8083
      #nodePort: 30450
