apiVersion: v1
kind: Service
metadata:
  name: javacoffeeshop
  namespace: keptndemo
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: javacoffeeshop
  ports:
      port: 8080
      targetPort: 8083
      nodePort: 30450
